---
title: "Grafico NUEVOS POR DÍA"
author: "Raquel P."
output: html_document
---




```{r}
install.packages("devtools") 
```


```{r}
devtools::install_github("JohnCoene/echarts4r") 
```

```{r}

library(echarts4r) 
```


```{r}

library(ggplot2)
library(dplyr)
library(gapminder)
library(tidyr)
library(rlang)
library(stringr)
```



```{r}
datosgenerales <- as.data.frame(read.csv("07_05_CSV_GENERAL.csv",header=TRUE,sep=";"))

datosgenerales <- datosgenerales %>%
    select(FECHA,nue_posi,NUE_RECUP,nue_falleci)%>%
    mutate(FECHA=as.Date(as.character(FECHA), format = "%d/%m/%Y"))


head(datosgenerales)

View(datosgenerales)
```












```{r}
datos %>% 
  e_charts(x = Fecha) %>% 
  e_bar(serie = Nuevos_Positivos, name ="Nuevos Casos Positivos") %>%  
  e_bar(serie = Nuevos_Recuperados, name ="Nuevos Casos De Recuperados") %>% 
  e_bar(serie = Nuevos_Fallecidos, name = "Nuevos Casos De Fallecidos") %>% 
  e_title("COVID-19 en Costa Rica (Nuevos Casos Por Día)","(Marzo-Junio, 2020)",tag = "Grafico 2") %>% 
  e_axis_labels(x="Día",y="No.Casos") %>% 
  e_theme("macarons") %>% 
  e_legend("bottom=0") %>%
  e_tooltip(trigger = "axis")
 
   
```














